### PR TITLE
fix write setup overwriting read setup.

### PR DESCRIPTION
**Pull request by tmclaugh**
Solves two issues
* only read values were being used.
* Write CFN resources overwrote the read resources.

Not familiar enough with TypeScript / JavaScript to know if there's more to be done.

### CODE REVIEW

**Comment by hotgazpacho** [comment]
Interesting, I just ran into this as well. Was wondering why my tables were being created with only write scaling...

**Comment by sbstjn** [comment]
Good catch, sorry for adding this bug with the last refactoring :)

**Comment by tmclaugh** [comment]
Anything I can do to speed up merge of this?  Just waiting on a personal project for work.

**Comment by sbstjn** [comment]
I just merged it and triggered a deployment for version `v0.6.1`. It should be on NPM in a few minutes. Thanks for your contribution! Feedback would be appreciated if the new version works fine.

**Pull request merged**
